Repository proofcarryingdata/zupass, pull requests merged in 2023-09, with the labels that each got.

#489 New Semaphore dependency versions
  apps/consumer-client/package.json
  apps/passport-client/package.json
  apps/passport-server/package.json
  packages/ethereum-group-pcd/package.json
  packages/ethereum-ownership-pcd/package.json
  packages/input-test-pcd/package.json
  packages/passport-interface/package.json
  packages/rln-pcd/package.json
  packages/semaphore-group-pcd/package.json
  packages/semaphore-identity-pcd/package.json
  packages/semaphore-signature-pcd/package.json
  packages/zk-eddsa-ticket-pcd/package.json
  yarn.lock
Labels: quality

#454 Support for hash routes in PCDpass popup
  packages/passport-interface/src/PassportPopup.ts
Labels: feature

#544 Fix field label in zkeddsa ticket example
  apps/consumer-client/pages/pcdpass-examples/zkeddsa-proof.tsx
Labels: bug

#580 New rudimentary missing README files
  packages/eddsa-pcd/README.md
  packages/rln-pcd/README.md
  packages/zk-eddsa-ticket-pcd/README.md
Labels: documentation

#583 Add default subscriptions after emitter listener is set up
  apps/passport-client/pages/index.tsx
Labels: performance

#647 New snarkjs/circomlibjs type definitions
  package.json
  packages/eddsa-pcd/src/EdDSAPCD.ts
  packages/eddsa-pcd/src/index.ts
  packages/eddsa-pcd/src/util/declarations/circomlibjs.d.ts
  packages/eddsa-pcd/test/EDDSAPCD.spec.ts
  packages/eddsa-pcd/tsconfig.json
  packages/util/src/declarations/circomlibjs.d.ts
  packages/util/src/declarations/snarkjs.d.ts
  packages/zk-eddsa-event-ticket-pcd/src/ZKEdDSAEventTicketPCD.ts
  packages/zk-eddsa-event-ticket-pcd/src/index.ts
  packages/zk-eddsa-event-ticket-pcd/test/ZKEdDSAEventTicketPCD.spec.ts
  packages/zk-eddsa-ticket-pcd/src/ZKEdDSATicketPCD.ts
  packages/zk-eddsa-ticket-pcd/src/index.ts
  packages/zk-eddsa-ticket-pcd/test/ZKEdDSATicketPCD.spec.ts
  yarn.lock
Labels: enhancement

#613 New way to manage artifacts for zk PCDs
  .github/workflows/build-and-test.yml
  apps/consumer-client/package.json
  apps/passport-client/.gitignore
  apps/passport-client/package.json
  apps/passport-client/public/zk-eddsa-event-ticket-artifacts-unsafe/eddsaEventTicket.wasm
  apps/passport-client/public/zk-eddsa-event-ticket-artifacts-unsafe/eddsaEventTicket.zkey
  apps/passport-client/public/zk-eddsa-event-ticket-artifacts-unsafe/verification_key.json
  apps/passport-client/public/zkeddsa-artifacts-unsafe/eddsaTicket.wasm
  apps/passport-client/public/zkeddsa-artifacts-unsafe/eddsaTicket.zkey
  apps/passport-client/public/zkeddsa-artifacts-unsafe/verification_key.json
  apps/passport-client/src/pcdPackages.ts
  apps/passport-server/.gitignore
  apps/passport-server/package.json
  apps/passport-server/public/zk-eddsa-event-ticket-artifacts-unsafe/eddsaEventTicket.wasm
  apps/passport-server/public/zk-eddsa-event-ticket-artifacts-unsafe/eddsaEventTicket.zkey
  apps/passport-server/public/zk-eddsa-event-ticket-artifacts-unsafe/verification_key.json
  apps/passport-server/public/zkeddsa-artifacts-unsafe/eddsaTicket.wasm
  apps/passport-server/public/zkeddsa-artifacts-unsafe/eddsaTicket.zkey
  apps/passport-server/public/zkeddsa-artifacts-unsafe/verification_key.json
  apps/passport-server/src/services/provingService.ts
  package.json
  packages/artifacts/.eslintrc.json
  packages/artifacts/CHANGELOG.md
  packages/artifacts/LICENSE
  packages/artifacts/README.md
  packages/artifacts/package.json
  packages/artifacts/src/commands/download.js
  packages/artifacts/src/commands/generate.js
  packages/artifacts/src/commands/listPackages.js
  packages/artifacts/src/commands/upload.js
  packages/artifacts/src/config.js
  packages/artifacts/src/index.js
  packages/artifacts/src/spinner.js
  packages/artifacts/src/utils.js
  packages/zk-eddsa-event-ticket-pcd/.gitignore
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/eddsaEventTicket.zkey
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/eddsaEventTicket_js/eddsaEventTicket.wasm
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/eddsaEventTicket_js/generate_witness.js
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/eddsaEventTicket_js/witness_calculator.js
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/generate_artifacts.sh
  packages/zk-eddsa-event-ticket-pcd/artifacts-unsafe/verification_key.json
  packages/zk-eddsa-event-ticket-pcd/circuits/index.circom
  packages/zk-eddsa-event-ticket-pcd/package.json
  packages/zk-eddsa-event-ticket-pcd/src/ZKEdDSAEventTicketPCD.ts
  packages/zk-eddsa-event-ticket-pcd/test/ZKEdDSAEventTicketPCD.spec.ts
  packages/zk-eddsa-ticket-pcd/.gitignore
  packages/zk-eddsa-ticket-pcd/artifacts-unsafe/eddsaTicket.zkey
  packages/zk-eddsa-ticket-pcd/artifacts-unsafe/eddsaTicket_js/eddsaTicket.wasm
  packages/zk-eddsa-ticket-pcd/artifacts-unsafe/generate_artifacts.sh
  packages/zk-eddsa-ticket-pcd/artifacts-unsafe/verification_key.json
  packages/zk-eddsa-ticket-pcd/circuits/index.circom
  packages/zk-eddsa-ticket-pcd/package.json
  packages/zk-eddsa-ticket-pcd/src/ZKEdDSATicketPCD.ts
  packages/zk-eddsa-ticket-pcd/test/ZKEdDSATicketPCD.spec.ts
  turbo.json
  typedoc.json
  yarn.lock
Labels: enhancement

#653 New `-nc` option to not download artifacts if they exist
  apps/passport-client/package.json
  apps/passport-server/package.json
  package.json
  packages/artifacts/README.md
  packages/artifacts/src/commands/download.js
  packages/artifacts/src/commands/generate.js
  packages/artifacts/src/commands/upload.js
Labels: enhancement
