Repository proofcarryingdata/zupass, pull requests merged in 2024-05, with the labels that each got.

#1675 Shared functionality to support upcoming GPC config
  apps/passport-client/package.json
  apps/passport-client/pages/index.tsx
  apps/passport-client/public/artifacts/.gitignore
  apps/passport-client/scripts/copy-test-artifacts.sh
  apps/passport-client/turbo.json
  package.json
  packages/lib/gpcircuits/circuits.json
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_1o-1e-5md.circom
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_1o-5e-8md.circom
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_3o-10e-8md.circom
  packages/lib/gpcircuits/package.json
  packages/lib/gpcircuits/scripts/gen-test-artifacts.sh
  packages/lib/gpcircuits/src/declarations/fastfile.d.ts
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/src/util.ts
  packages/lib/gpcircuits/test/common.ts
  packages/lib/gpcircuits/test/entry.spec.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/lib/gpcircuits/turbo.json
  packages/lib/pod/package.json
  packages/lib/pod/src/podContent.ts
  packages/lib/pod/src/podCrypto.ts
  packages/lib/pod/src/podUtil.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podUtil.spec.ts
  packages/pcd/pod-pcd/package.json
  packages/pcd/pod-pcd/src/PODPCD.ts
  packages/ui/pod-pcd-ui/package.json
  turbo.json
Labels: feature

#1672 Refactor ProtoPODGPC artifact and circuit generation code
  packages/lib/gpcircuits/circuits.json
  packages/lib/gpcircuits/package.json
  packages/lib/gpcircuits/scripts/gen-circuit-parameters.ts
  packages/lib/gpcircuits/scripts/gen-test-artifacts.ts
  packages/lib/gpcircuits/scripts/util.ts
  packages/lib/gpcircuits/src/circuitParameters.json
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/src/util.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/lib/gpcircuits/tsconfig.cjs.json
  packages/lib/gpcircuits/tsconfig.esm.json
  packages/lib/gpcircuits/turbo.json
  yarn.lock
Labels: feature

#1681 Fix & cleanup gpcircuit parameters
  packages/lib/gpcircuits/scripts/gen-circuit-parameters.ts
  packages/lib/gpcircuits/scripts/gen-test-artifacts.sh
  packages/lib/gpcircuits/scripts/gen-test-artifacts.ts
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/lib/gpcircuits/tsconfig.cjs.json
  packages/lib/gpcircuits/tsconfig.esm.json
  packages/lib/gpcircuits/tsconfig.json
  packages/lib/gpcircuits/turbo.json
Labels: bug, cleanup

#1664 Upgrade zk-kit packages
  packages/lib/pod/package.json
  packages/lib/pod/test/common.ts
  packages/lib/pod/test/podCrypto.spec.ts
  packages/lib/pod/tsconfig.json
  yarn.lock
Labels: test, security

#1688 GPC-related Cleanups
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpcircuits/circuits/entry.circom
  packages/lib/gpcircuits/package.json
  packages/lib/gpcircuits/src/list-membership.ts
  packages/lib/gpcircuits/src/tuple.ts
  packages/lib/gpcircuits/test/list-membership.spec.ts
  packages/lib/gpcircuits/test/multituple.spec.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  yarn.lock
Labels: cleanup

#1689 Typedoc errors
  packages/lib/client-shared/typedoc.json
Labels: bug

#1708 GPC artifact download support
  apps/consumer-client/.env.example
  apps/consumer-client/build.ts
  apps/consumer-client/package.json
  apps/consumer-client/src/constants.ts
  apps/consumer-client/src/pages/examples/add-pcd.tsx
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  apps/consumer-client/tsconfig.json
  apps/passport-client/.env.example
  apps/passport-client/build.ts
  apps/passport-client/package.json
  apps/passport-client/public/artifacts/.gitignore
  apps/passport-client/src/pcdPackages.ts
  apps/passport-client/tsconfig.json
  apps/zupoll-server/tsconfig.json
  packages/lib/client-shared/src/index.tsx
  packages/lib/client-shared/src/util.ts
  packages/lib/gpc/package.json
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpcircuits/package.json
  packages/lib/gpcircuits/scripts/copy-test-to-snark-artifacts.sh
  packages/lib/gpcircuits/src/artifacts.ts
  packages/lib/gpcircuits/src/index.ts
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/src/util.ts
  packages/lib/gpcircuits/test/artifacts.spec.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  turbo.json
  yarn.lock
Labels: feature

#1722 Don't fail build when dir doesn't exist
  apps/passport-client/build.ts
Labels: bug

#1721 Test gpc-pcd against artifacts both locally-built and NPM-released
  packages/pcd/gpc-pcd/package.json
  packages/pcd/gpc-pcd/test/gpc-pcd.spec.ts
Labels: test

#1727 POD + GPC Example code
  examples/pod-gpc-example/.eslintrc.js
  examples/pod-gpc-example/.gitignore
  examples/pod-gpc-example/LICENSE
  examples/pod-gpc-example/README.md
  examples/pod-gpc-example/package.json
  examples/pod-gpc-example/src/gpcExample.ts
  examples/pod-gpc-example/src/index.ts
  examples/pod-gpc-example/src/podExample.ts
  examples/pod-gpc-example/test/pod-gpc-example.spec.ts
  examples/pod-gpc-example/tsconfig.cjs.json
  examples/pod-gpc-example/tsconfig.esm.json
  examples/pod-gpc-example/tsconfig.json
  examples/pod-gpc-example/turbo.json
  examples/pod-gpc-example/typedoc.json
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/src/gpcTypes.ts
  tsconfig.cjs.json
  tsconfig.esm.json
Labels: documentation, test

#1730 Let pod-ticket-pcd be published
  packages/pcd/gpc-pcd/package.json
  packages/pcd/pod-ticket-pcd/package.json
  packages/ui/gpc-pcd-ui/package.json
Labels: bug

#1734 Add list non-membership checks to GPC
  apps/passport-client/package.json
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcCompile.ts
  packages/lib/gpc/src/gpcTypes.ts
  packages/lib/gpc/src/gpcUtil.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpcircuits/circuits.json
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_1o-5e-6md-0x0l-0x0t.circom
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_3o-10e-8md-1x10l-2x2t.circom
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_3o-10e-8md-2x20l-1x4t.circom
  packages/lib/gpcircuits/circuits/main/proto-pod-gpc_3o-10e-8md-4x20l-5x2t.circom
  packages/lib/gpcircuits/circuits/proto-pod-gpc.circom
  packages/lib/gpcircuits/src/circuitParameters.json
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/pcd/gpc-pcd/package.json
  yarn.lock
Labels: feature

#1735 Missed artifact version update
  examples/pod-gpc-example/package.json
  yarn.lock
Labels: bug

#1742 Detailed docs and links in READMEs for POD+GPC
  apps/passport-client/scripts/copy-test-artifacts.sh
  packages/lib/gpc/README.md
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpcircuits/README.md
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/pod/README.md
  packages/lib/pod/src/pod.ts
  packages/lib/pod/src/podContent.ts
  packages/pcd/gpc-pcd/README.md
  packages/pcd/pod-pcd/README.md
  packages/ui/gpc-pcd-ui/README.md
  packages/ui/pod-pcd-ui/README.md
Labels: documentation
