Repository proofcarryingdata/zupass, pull requests merged in 2024-10, with the labels that each got.

#1911 Remove circomlibjs dependency in favor of zk-kit
  .vscode/launch.json
  apps/consumer-client/package.json
  apps/passport-server/package.json
  apps/zupoll-client/package.json
  package.json
  packages/lib/gpc/package.json
  packages/lib/gpcircuits/package.json
  packages/lib/pod/package.json
  packages/pcd/eddsa-pcd/package.json
  packages/pcd/eddsa-pcd/src/EDDSAPCDPackage.ts
  packages/pcd/semaphore-identity-pcd/package.json
  packages/pcd/zk-eddsa-event-ticket-pcd/package.json
  packages/pcd/zk-eddsa-event-ticket-pcd/src/ZKEdDSAEventTicketPCDPackage.ts
  packages/pcd/zk-eddsa-frog-pcd/package.json
  packages/pcd/zk-eddsa-frog-pcd/src/ZKEdDSAFrogPCDPackage.ts
  test-packaging/zupass-feed-server/package.json
  yarn.lock
Labels: cleanup

#1920 Stricter object type checking
  packages/lib/pod/src/podChecks.ts
  packages/lib/pod/src/podContent.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podUtil.spec.ts
  packages/ui/pod-ticket-pcd-ui/tsconfig.cjs.json
  packages/ui/pod-ticket-pcd-ui/tsconfig.esm.json
  packages/ui/pod-ticket-pcd-ui/tsconfig.json
Labels: bug

#1940 Split podUtil.spec.ts in the same way as podUtil.ts was split
  packages/lib/pod/test/podChecks.spec.ts
  packages/lib/pod/test/podSerialization.spec.ts
  packages/lib/pod/test/podUtil.spec.ts
Labels: test

#1916 PODValue JSON Encoding
  examples/pod-gpc-example/src/gpcExample.ts
  examples/pod-gpc-example/src/podExample.ts
  packages/lib/pod/src/index.ts
  packages/lib/pod/src/pod.ts
  packages/lib/pod/src/podChecks.ts
  packages/lib/pod/src/podContent.ts
  packages/lib/pod/src/podJSON.ts
  packages/lib/pod/test/pod.spec.ts
  packages/lib/pod/test/podChecks.spec.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podJSON.spec.ts
  packages/lib/podspec/test/podspec.spec.ts
Labels: feature

#1910 Refactor GPC artifact generation
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/index.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpcircuits/.gitignore
  packages/lib/gpcircuits/package.json
  packages/lib/gpcircuits/scripts/common.ts
  packages/lib/gpcircuits/scripts/copy-snark-artifacts.sh
  packages/lib/gpcircuits/scripts/gen-artifacts.ts
  packages/lib/gpcircuits/scripts/gen-circuit-parameters.ts
  packages/lib/gpcircuits/scripts/gen-test-artifacts.ts
  packages/lib/gpcircuits/scripts/parameters/README.md
  packages/lib/gpcircuits/scripts/parameters/paramGen.json
  packages/lib/gpcircuits/scripts/parameters/testParamGen.json
  packages/lib/gpcircuits/scripts/util.ts
  packages/lib/gpcircuits/src/artifacts.ts
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/src/testCircuitParameters.json
  packages/lib/gpcircuits/test/artifacts.spec.ts
  packages/lib/gpcircuits/test/list-membership.spec.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/lib/gpcircuits/testCircuits.json
  packages/lib/gpcircuits/tsconfig.cjs.json
  packages/lib/gpcircuits/tsconfig.esm.json
  packages/lib/gpcircuits/tsconfig.json
  packages/lib/gpcircuits/turbo.json
  packages/pcd/gpc-pcd/src/GPCPCD.ts
  packages/pcd/gpc-pcd/src/GPCPCDPackage.ts
  packages/pcd/gpc-pcd/test/validatorChecks.spec.ts
Labels: feature

#1952 Remove old pod serialization
  apps/consumer-client/.env.example
  apps/consumer-client/src/constants.ts
  apps/consumer-client/src/pages/examples/add-pcd.tsx
  apps/passport-client/src/mintUtils.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/PODPipeline.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/utils/atomize.ts
  packages/lib/pod/package.json
  packages/lib/pod/src/index.ts
  packages/lib/pod/src/pod.ts
  packages/lib/pod/src/podContent.ts
  packages/lib/pod/src/podSerialization.ts
  packages/lib/pod/test/pod.spec.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podSerialization.spec.ts
  turbo.json
Labels: feature, cleanup

#1943 Use JSONPODValue in POD-PCD and GPC-PCD
  apps/consumer-client/.env.example
  apps/consumer-client/src/constants.ts
  apps/consumer-client/src/pages/examples/add-pcd.tsx
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  apps/consumer-client/src/podExampleConstants.ts
  apps/consumer-client/tsconfig.json
  apps/passport-client/src/dispatch.ts
  apps/passport-client/src/mintUtils.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/PODPipeline.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/utils/atomize.ts
  examples/pod-gpc-example/src/gpcExample.ts
  examples/pod-gpc-example/src/podExample.ts
  packages/lib/gpc/package.json
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcJSON.ts
  packages/lib/gpc/src/gpcSerialize.ts
  packages/lib/gpc/src/gpcTypes.ts
  packages/lib/gpc/src/index.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpc/test/gpcJSON.spec.ts
  packages/lib/gpcircuits/tsconfig.cjs.json
  packages/lib/gpcircuits/tsconfig.esm.json
  packages/lib/passport-interface/src/api/requestUpgradeUserWithV4Commitment.ts
  packages/lib/passport-interface/test/V3ToV4Migration.spec.ts
  packages/lib/pod/package.json
  packages/lib/pod/src/index.ts
  packages/lib/pod/src/pod.ts
  packages/lib/pod/src/podContent.ts
  packages/lib/pod/src/podJSON.ts
  packages/lib/pod/src/podSerialization.ts
  packages/lib/pod/src/podUtil.ts
  packages/lib/pod/test/pod.spec.ts
  packages/lib/pod/test/podChecks.spec.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podJSON.spec.ts
  packages/lib/pod/test/podSerialization.spec.ts
  packages/pcd/gpc-pcd/src/GPCPCD.ts
  packages/pcd/gpc-pcd/src/GPCPCDPackage.ts
  packages/pcd/gpc-pcd/src/util.ts
  packages/pcd/gpc-pcd/test/gpc-pcd.spec.ts
  packages/pcd/gpc-pcd/test/util.spec.ts
  packages/pcd/pod-pcd/src/PODPCD.ts
  packages/pcd/pod-pcd/src/PODPCDPackage.ts
  packages/pcd/pod-pcd/test/PODPCD.spec.ts
  packages/tools/perftest/src/cases/GPCTimer.ts
  packages/tools/perftest/src/cases/PODTimer.ts
  packages/ui/pod-pcd-ui/src/renderers/DefaultPODPCDCardBody.tsx
  turbo.json
Labels: feature

#1989 Add deriveSignerPublicKey helper function
  packages/lib/pod/src/podCrypto.ts
  packages/lib/pod/test/podCrypto.spec.ts
Labels: enhancement

#1990 Review and update TODO(POD-*)
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcJSON.ts
  packages/lib/gpc/src/gpcTypes.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpc/test/gpcChecks.spec.ts
  packages/lib/gpc/test/gpcCompile.spec.ts
  packages/lib/gpc/test/gpcUtil.spec.ts
  packages/lib/gpcircuits/circuits/bounds.circom
  packages/lib/gpcircuits/circuits/entry.circom
  packages/lib/gpcircuits/circuits/object.circom
  packages/lib/gpcircuits/circuits/proto-pod-gpc.circom
  packages/lib/gpcircuits/src/proto-pod-gpc.ts
  packages/lib/gpcircuits/test/proto-pod-gpc.spec.ts
  packages/lib/pod/src/podCrypto.ts
  packages/lib/pod/src/podUtil.ts
Labels: cleanup

#1986 Expose functions to allow external provers/verifiers
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/src/index.ts
  packages/lib/gpc/test/gpc.spec.ts
Labels: enhancement

#1983 Use JSON for GPCProofConfig and GPCRevealedClaims
  apps/consumer-client/src/pages/examples/add-pcd.tsx
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  examples/pod-gpc-example/src/gpcExample.ts
  packages/lib/gpc/src/gpcSerialize.ts
  packages/lib/gpc/src/index.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpc/test/gpcChecks.spec.ts
  packages/lib/gpc/test/gpcUtil.spec.ts
  packages/pcd/gpc-pcd/src/GPCPCD.ts
  packages/pcd/gpc-pcd/src/GPCPCDPackage.ts
  packages/pcd/gpc-pcd/src/index.ts
  packages/pcd/gpc-pcd/src/json.ts
  packages/pcd/gpc-pcd/test/gpc-pcd.spec.ts
  packages/pcd/gpc-pcd/test/validatorChecks.spec.ts
  packages/tools/perftest/src/cases/GPCTimer.ts
  packages/ui/gpc-pcd-ui/src/CardBody.tsx
Labels: feature

#2007 Show deserialization error properly
  apps/passport-client/components/screens/AddScreen/JustAddScreen.tsx
  apps/passport-client/src/useDeserialized.tsx
Labels: bug

#1963 JSON format for GPCs using Valibot
  apps/consumer-client/src/pages/examples/add-pcd.tsx
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  apps/passport-client/components/screens/AddScreen/JustAddScreen.tsx
  apps/passport-client/src/useDeserialized.tsx
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/PODPipeline.ts
  examples/pod-gpc-example/src/gpcExample.ts
  packages/lib/gpc/package.json
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcJSON.ts
  packages/lib/gpc/src/gpcSerialize.ts
  packages/lib/gpc/src/gpcTypes.ts
  packages/lib/gpc/src/gpcUtil.ts
  packages/lib/gpc/src/gpcValibot.ts
  packages/lib/gpc/src/index.ts
  packages/lib/gpc/src/valibot/bigint.ts
  packages/lib/gpc/src/valibot/boundConfig.ts
  packages/lib/gpc/src/valibot/circuitIdentifier.ts
  packages/lib/gpc/src/valibot/closedInterval.ts
  packages/lib/gpc/src/valibot/membershipLists.ts
  packages/lib/gpc/src/valibot/podEntries.ts
  packages/lib/gpc/src/valibot/podEntryIdentifier.ts
  packages/lib/gpc/src/valibot/podName.ts
  packages/lib/gpc/src/valibot/podValue.ts
  packages/lib/gpc/src/valibot/proofConfig.ts
  packages/lib/gpc/src/valibot/proofEntryConfig.ts
  packages/lib/gpc/src/valibot/proofEntryConfigCommon.ts
  packages/lib/gpc/src/valibot/proofObjectConfig.ts
  packages/lib/gpc/src/valibot/proofTupleConfig.ts
  packages/lib/gpc/src/valibot/revealedClaims.ts
  packages/lib/gpc/src/valibot/revealedObjectClaims.ts
  packages/lib/gpc/src/valibot/valibotUtil.ts
  packages/lib/gpc/test/gpcChecks.spec.ts
  packages/lib/gpc/test/gpcJSON.spec.ts
  packages/lib/gpc/test/gpcValibot.spec.ts
  packages/lib/pod/src/podChecks.ts
  packages/lib/pod/src/podJSON.ts
  packages/pcd/gpc-pcd/src/GPCPCD.ts
  packages/pcd/gpc-pcd/src/GPCPCDPackage.ts
  packages/pcd/gpc-pcd/src/index.ts
  packages/pcd/gpc-pcd/src/json.ts
  packages/pcd/gpc-pcd/test/gpc-pcd.spec.ts
  packages/pcd/gpc-pcd/test/validatorChecks.spec.ts
  packages/tools/perftest/src/cases/GPCTimer.ts
  packages/ui/gpc-pcd-ui/src/CardBody.tsx
Labels: feature

#1988 pod_type usage in Zupass
  apps/passport-client/src/zapp/ZappServer.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PretixPipeline.ts
  examples/pod-gpc-example/src/gpcExample.ts
  packages/lib/passport-interface/src/api/requestUpgradeUserWithV4Commitment.ts
  packages/lib/passport-interface/test/V3ToV4Migration.spec.ts
  packages/lib/pod/README.md
  packages/pcd/pod-pcd/test/PODPCD.spec.ts
  packages/pcd/pod-ticket-pcd/src/utils.ts
  packages/pcd/pod-ticket-pcd/test/pod-ticket-pcd.spec.ts
Labels: enhancement

#2042 Fix quirks of GPC artifact config and build
  apps/passport-client/build.ts
  apps/passport-client/components/screens/EmbeddedScreens/EmbeddedGPCProofScreen.tsx
  apps/passport-client/src/pcdPackages.ts
  apps/passport-client/src/sharedConstants.ts
  apps/passport-client/src/util.ts
  apps/passport-client/src/zapp/ZappServer.ts
  packages/lib/client-shared/package.json
  packages/lib/client-shared/src/util.ts
  packages/lib/client-shared/tsconfig.cjs.json
  packages/lib/client-shared/tsconfig.esm.json
  packages/lib/client-shared/tsconfig.json
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/test/gpc.spec.ts
Labels: bug

#2043 Add jsdelivr for artifact download, and make it the default
  apps/consumer-client/.env.example
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  apps/passport-client/.env.example
  apps/passport-client/src/sharedConstants.ts
  examples/pod-gpc-example/src/gpcExample.ts
  packages/lib/client-shared/src/util.ts
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpcircuits/src/artifacts.ts
  packages/lib/gpcircuits/test/artifacts.spec.ts
Labels: enhancement

#2047 Don't return early in service worker
  apps/passport-client/src/worker/service-worker.ts
Labels: bug

#2046 4 new PODValue types
  apps/passport-client/components/screens/EmbeddedScreens/EmbeddedGPCProofScreen.tsx
  apps/passport-client/components/screens/EmbeddedScreens/EmbeddedSignPODScreen.tsx
  apps/passport-client/components/shared/uiUtil.ts
  apps/passport-server/src/services/generic-issuance/pipelines/PODPipeline/PODPipeline.ts
  examples/pod-gpc-example/src/gpcExample.ts
  examples/pod-gpc-example/src/podExample.ts
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcCompile.ts
  packages/lib/gpc/src/valibot/podValue.ts
  packages/lib/gpc/test/common.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/lib/gpc/test/gpcValibot.spec.ts
  packages/lib/gpcircuits/src/util.ts
  packages/lib/pod/src/podChecks.ts
  packages/lib/pod/src/podCrypto.ts
  packages/lib/pod/src/podJSON.ts
  packages/lib/pod/src/podTypes.ts
  packages/lib/pod/src/podUtil.ts
  packages/lib/pod/test/alternateCrypto.ts
  packages/lib/pod/test/common.ts
  packages/lib/pod/test/podChecks.spec.ts
  packages/lib/pod/test/podContent.spec.ts
  packages/lib/pod/test/podCrypto.spec.ts
  packages/lib/pod/test/podJSON.spec.ts
  packages/lib/pod/test/podTypes.spec.ts
  packages/lib/pod/test/podUtil.spec.ts
Labels: feature

#2056 GPC Semaphore V4 enhancements for example
  apps/consumer-client/src/pages/examples/gpc-proof.tsx
  apps/passport-client/tsconfig.json
  examples/pod-gpc-example/package.json
  examples/pod-gpc-example/src/gpcExample.ts
  examples/pod-gpc-example/src/podExample.ts
  packages/lib/gpc/src/gpc.ts
  packages/lib/gpc/src/gpcChecks.ts
  packages/lib/gpc/src/gpcCompile.ts
  packages/lib/gpc/test/gpc.spec.ts
  packages/pcd/gpc-pcd/src/GPCPCDPackage.ts
  yarn.lock
Labels: enhancement
